AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FinalNewline:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100
