require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GroupsController, type: :controller do
  let(:user) { FactoryGirl.create :user }

  # This should return the minimal set of attributes required to create a valid
  # Group. As you add validations to Group, be sure to
  # adjust the attributes here as well.

  let(:group) { FactoryGirl.create :valid_group, user_id: user.id  }
  let(:image) { image = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFhUXGBkaGBcXGRgaFRgXGB0WFxUaHhcYHSggGBolHRcXITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGxAQGy0lICUvLS0tLS0vLy8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAKgBLAMBEQACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAAAwQCBQYBB//EAEkQAAIBAgMFBQUEBgcFCQAAAAECAAMRBBIhBQYxQVEiYXGBkRMyQqGxFFLB0QcjcpLh8BUWQ2KCstIzU1SDkyQ0VZSio8LT8f/EABoBAQADAQEBAAAAAAAAAAAAAAABAgMEBQb/xAA3EQACAQIEAwUIAgEEAwEAAAAAAQIDEQQSITETQVEFFGGRoSIyQnGBsdHwUsHhFSNTYkOi0jP/2gAMAwEAAhEDEQA/APuMAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQDX7Z2xSwyZqjcfdUe8x7h+MpOpGCuzSlSlUdomk2VvpTqVcjFVBGncR1N7cL+FpjTxCk7HRVwcoRujq50nGRYjEpTF3dUHViAPUyG0tyUm9jUYne3CJoat/2QSPW1vnM3XguZtHDVZa2MMDvhhKrimKlmJsuYWBJ4C/C/jEa0G7EywtSKvY381OcQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAhxFfLyJ/nukN2LRVyv9sb7p9PzlM/gWyeJi2Lf7h/8ATI4j6E5F1IWxlX7h9U/OVdSXQsqcOppto7OSs2erhhUbqzX8gM2g7hMpNveJtD2VZSKa7IpDVcHTFteQOngZS/8A1NG3tnZsKW0q6KEWnZQLAXvYdL3l1Wn0MnRg9blZ1zm7YYMepJJ9Sbybt7xJSttIxOy6Le9hD6v+BkqKfwk8Sa2kV13TwWo+y1RcWNnrWt5mTw4fxI49X+X2OqwmLCIq2qWUAAsCTYcLsdSe86zdSWxzOPMsDHiTmRXKyejWDSSGrEsECAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgGu3hr1Uw9R6KB6oF1U8CbjvHfzlZu0TbDxhKqozdlzPnLbx7Y+JcFR/aqUx8jWMwcme2sJguTk/kn/8AJXfeLaX/AB2zV8KtG/4yrm+posJhE/8A85+UitV29tH/AMTwIPc9H/6zIz/tzTu+EX/il5S/JXfbm0dL7Uwfk1G/j/s4zIjgYf8A4peT/JE23Mfa39JYS975s9Hh0t7O0i6I4ND/AI35P8kR29tLltHCH/Hh/wDTJzIjgUH/AON+Uiwu8m0RwxmCbxqYYa+ovJUiHh8O/hl5Mt4Xefadz+swbdm4tVw3vctPbC635yybtoQ8HhnupeUvwbGjvNti4/7PhnGl7VKZPfbLVls0ijwWC5ykvP8AuJffenagOmzlIsLZSza8/dJ7+UZpdDJ4HB/8v75ELb/45P8Aa7JrAcyPaAD1pkfOW4j5of6ZRfu1V6fk7/YmL9rQp1QhTOobKeIvrY980i7q549aHDqOF72di9JMxAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQCDHUFem6OoZWUgqwuCOhB4iQ9i0JOMk0c5u79lrIzUsOlPI7U2U00VlZe4DmCGHcRMVZ8jurutCSUpN3V92bn2Kjgq+QEk580upxW82/iYWrlFFalNWyOy1aftFbW49kLm2hsWtcg8NCaN9D0sPgJVYXcmnutHbz/B1FGstRFqJYq6hlPUMLg+hEXRwuMoycXuiJ1BPuj5Sou+pXxbolNqjAZVBJ0HKHsXgpSllRx2G35o/aEo1cKqI9stQPSqDtGykhAQBfjZjaIs75YKahmjN3XzO7XZ1E/wBjT/cX8pskjzHVqX95+Zl/QuGPHD0T/wAtPyk5V0J7zWW035s1m3dmbOw9M1auDpsACT7OgGaw1JOUaKOZJAkOMFq0dGHq4utPLGo7+Mv278CXB7CwVWklWijKjqGU06lWnoe5HFvCWypmdTE4iE3GbTa01Sf9HUYSkERVBJCqBdiWY2FtWOrHvMulY4JSzNslggQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAxqjQ+BkPYlbnxn9HG0KuExz4Bu0ju99OFRRowbiQQliOs5oaH03aVOFajx47q3kz6vic2RsurWOUdWtp85o9jwI2ur7HwTfLdZ8LVsCahZWqMAMzU1vYM7DQZrE9BqLm15nF20Z9VhcUq0b2ty+fy+Rtv0db14gVqeGqNnotamoI1pmxyWYDUWUixPeOBkSVnoc2OwtNwc1o9/mfVmEg8I5TfvZNbFolClfKSzsb2BYZVpgn7t2ZzxPY0FyJVux34OcKbcpHx/HYI0aj0xZ/Z1CvtEvlJW9wD5X8jNL3PapyUo7b6+J9T/AEZ731sTVfD1znITOjlVVtCAysF0+IW8Ne68G1ozx+0cJTpxU4acrH0hBNDyGfL/ANLGGxLFq+YrQpWQLqAS/ZZh1JJZSOGVBr2rTNt3uz3+yalOEeH8UtX9P1fV+Btv0SbcNbDNh2AvhwtmF+0tTOdb8wQR6S8HyOPtaioVFUT977o+krNDxj2AIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCADAOV2bsRPtH2oi75Mo8yxOnmf3u4TnUdbno1cS3T4S2ub6XOO5xexsF9sw+MqM1vtdR0DDUihTJoqBfuV/NrzFK9z1K9TgzpxS9xXt4vW/2M93N06WGzOUXOahdQCSKagMlNR95grNc9XaLFcRjJVNE9LefU3j98hnImc/vttN8PhHNP/aVCKdO3HNU007wLnyEg68JTVSprstSvi90VOEoYZdVonOUBy+1qhWGr/ApZiSdTbhLpFo4y1WU3z0+SNnuhutSwVNQO1VykPU63OZrDkNFHfkWaxRz4rFyrS8Oh06CWONmgxiHE4t0AUrhqVwG1Q4msGCZtPhpj/wB2Q9ZW6HZB8Gipc5Pl/Fb+b+xjuPuwuCpMADnqNqTxyqWFO/eVNyOV7cpaCsiuNxTxEl0X97nYSxwCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIAgCAIByVXeNaTtS+z4tyrEZqdBmQ68m4GYOSR6EMK5xUs0V82ZU95QxyjC4tNG7VSiVRbAm5YnQaRmHdba54v5PU0u7O2fYYHCp9mxNS9ENmpU869otcXuO1oTbvEzi9DqxNDiV5vNFa83Z7IuvvSOJwWO/6B+gaTmMFhf+8fMrNvaP+Ex3/l2/OVuX7m/5R8zSby7RWvV2cuSqgbElstRCj3p5LHKeXbldzpoQ4cajunpy+p0H9a6Skg0MVobXGHqW000IE1Ukcbws3s15k1PfChzp4keOHrfgsspoo8HU6rzRYpb44UkD9cCSAL4euBc6DUpYS3EiQ8JVtpbzRT2HtqjSbEvVZg1bFVStkqP2KYSkl8imwstxfjc2lYTirts1r0JzyRgtormuevM3mH3gw7EAVCLn4kqKPVlAEvxYdTklh6qW32NsuPpHhVQ+DL+cspxfMwcJLkTqwPCWKnsAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEAohbFh3n5m/4zN7mi2PKqBlKngQQfA6GQyydndFTZ2AShSSjTBCILLc3NvEyiVkaVKkqknOW7JXEqQiu5kX0LI53b+Dwz1qFatUIfDksiqeJOU6qAT8I6TGdWEH7TO2g6uWUYK9+ZHid67aU083/0j85zy7QS91F4dnt+8/I1VfeGu3Gow7l7P01nPLHTlzOmOBpx+EoVccx1ZifEkn5zPjt8zZUEtkZLjukcew7uZf0kecusSV4A+3yVXI4BJS2gw1UkHqLj6S8cQ+TM5YdPdGywm8+IT+0LDo3a+Z1+c3jjJI55YKnLkb7Z++6nSsmX+8mo81Oo+c6qeNi/eOSp2fNe6dRhMWlVc1Ngw6g/Xoe6dcZKSujhlGUXaSsTyxUQBAEAQBAEAQBAEAQDwm3GQ3bcAGE7g9kg8vAPA4PMSFJMWMpIEAQBAIquIVeJA+vpM51YQ95lowlLZFKptZQfdNuZ/hOSePhF7aHRHCya3JSbknrY/ITqvfUxSPTIbJIzKlyDEOFBYkADUkzOUlHV7F4xcnZHJbS20z3FO6r1+I/6Z4mI7QcnlhovU9rD4CMdamr6GifDkmcOeTPRtFBME3SVbkM0EZNspj1krP0I4sDH+iz0kPP0HFiQVMERGZl1JPYgbDGSpixilLWWzkNFhKEtmKOyJlw8vGbMnYkXDGaqTKOxJhK1Wi+ek5U/I9xHAibU8RODvFmNSjCorSR9B3d2+uJBUjLVUdpeRH3l7vpPaw2JjWXieHicLKi+q6m6nUcogCAIAgCAIAgCAIBpdtYwH9Wp4e9+AnldoV01w0/n+DuwtJp52vl+TnKNYq1s4vzsZ4UKuR2UvU9WUFJe6XW2kF0aodepM3ljLK0pO/1MFhs20TF9okaBjl6X0lJ41wWWMtCVhk3drUko4kcjr46zShiE1dPUpOk+aL9HaNQc7jv1nfDGVYvU5pYaD2LQ2sfuj1t+E6O/tfD6/wCDLuq6mX9Lcewb+ItLrHpr3SvdX1KeI2kx4nToNB+c4q2MnLn5HRDDRRS+1A8wBOSNXNq2dHCsTJhKjcEPidPrN44arNaR89DN1qcd2WtoYGsXvTrmmOybZQ2oBHPkdNO6ezKEuTOSjVpqPtwvvzNdU2fjlXKMWmUM2V2pg1CjBgM50UspIIsBewv0NHmXM6VWwzd+HrzSel105687/QgIx6slQYjD1bi1Si3YprpxSqAXvfjmGvICZOqv5LzL2w7Tjkkuj3f1WxrMW+ILtRq1VqAPcFFyixAYAi/wkkDU6AEkmeR2hWlOSpR25ndh4Uox4sVb5/vMlpYPunLToW1kaSrEy4cDpN1GMTJ1Lki0Za1yrmZtS6GXylM5Xq0eOso4M0jVRSbDk98o6Texqq6RXq4M8Ji8NJF1iVuVXw1jIVJrc0VZMmp0ppFcikqhOEAl4xSZm5XRYpqOk6E4mbuYNREhuJZSZFTLUnWomjKdO/qD3EaSqm6clOPITgqkXGR9IwWJFSmrrwYX8Oo8QdJ9HTmpwUlzPnJwcJOL5E8uUEAQBAEAQDX7Z2gaK3A1PA/CD3/lOLG4ru9PNb8HRhqHFla5yOI21UJ1qNf0HoJ85LtGpJ+1J/vyPajgoJaRRYwO36o+LMOh1+fETqodpVY87/vUxq4Gm+VijiGqFLLqb+BnnTzz5nXBQi9VoU6Wyqt7nQ955+V5msPOfRGrxEEW6eCqEWe1vHUSFh57NopKtBO6JaGDZRq6nu1I9ZqqKirSkvlYzlVUnpFk7YZeWh+Uh0YctCqqy5kYFQcKgty0v+MmPEj8RLyP4S0lU21a57lt+M6Y1nbV+n+TFxV9EFq9WOnd/GFiFzbJcPA8q4kcDrfmZEsTFvURpvdFQ4BWObM3cpOkzdKM7O5rxpR0sSVK2TibecmcnDRsiMFPZE+Hx1xdW9DNqdefwsynRit0eVKpOp18YbnLVsJKOiIfblbE8P56TL2luaZU9iuK6Bybi5N/WaRlG92XSeWxk+1EU8RIliFfRDgSa1MKm0FtflfrM+LfSw4bRUrbxUl+NdD94TozTa0iyOF1NdU3uo3P6xfUS2Sr/EhwR6N7KHN19ZaEKnNFJQ6GY3tw/KpNVdcinCkYf1loH+0Em76DhSPH25ROucSrafIuqbMF2zRbhUW/iNZk1bXKy+Ro2NHFKed/CV4seaIySLFLE35Wl4VIy2Kzi0TUawJM0VmVeZIyCBvrIyZiVUaR1m7S2o26M1vDQ/UmexglalbxZ5WMd6tzbTrOUQBAEAQBANDjdvaEIvm3+nnPDxPayScacdfH8Ho0sC205vyNKiXu2RAT3KP/AM8p5EXKTzOKv9Dvdl7N36kjhuo9T+UtLPLmQnFciPKw6esrkkly8y2aLPFL9PmNPnKx4nQl5DKpRbkQR3kg/SS6U76NfUiM480a7EYqoh1pNbqLN9DKOM07HRGNOWz/AKMcPtM1DlVDccb8vHpIbnJ2sTKlGCu2bN8OSBmYA9Brbzm8qF9W9TmjUs9FoEo6e98v4yqpaNXDnrsYtTIBsb36j8jKOi0rolSTepW9i9x7vnczNUn1Nc8SxToNyI/d/jN408uz9P8AJm5x5r1Mir8wp9fyl/aK3hyMST0Hr/CWUlfUHpvy1tL3siuj3K1etU5Jx7xMpTk3oi8IxW7In2WhOaoWuRqqnQefH5iVlOMd9WSqk3pBEdajhRcmkh/aseHiDKKs9o38/wAItao95Guxm2MImh9gpA4WXNbw/hN4UsRNXUdPr/bsVbinZyNHi958IeanS+lMjy90TpWDxP7Yrxaa6mvr7dwdhobnkEN/na00jhMS+fqRx4LZehSbauFJ0QnysfnLLDV1uyeNFvQmw+3MMNMjAd6gr48T9JEsJXtpJE8WN9UbKhtHBt/u/wDEAP8ANacsqGJT28jVVIW3LNDaeBDW/Ug+C/WZSo4pK7uSpwfNHQYLEUKosBScdLKZySnWpO7uvMWjLZlunsTDHVaSqf7oy/SdVLEuejZjLNEnbZNMiwzDwJmtkV4jIf6FZRalUt+0L/MEW9JCVuZPFT95GOCw9Y1Vo2sWJAbiugJOvgDpOminUkop7la0oKLn0PomFw4pqFHAfPqZ9BCChHKjwpScndk0uVEAQBANJtjaIuaYuLWudb37p5GPxijemuW7O7DYdv2zWpVsbqzA/tGebGrZ5oyfmzscLq0kvIgfDg8z6+s55U09bmqm1yMTSZQOJtzkShJJW5E5k2U8RiHOiqb9bX+kylUm/dTubQpwWsmiCk2I+4T42H1N5EY12i8uB1LVMVQe0gA/aE2UaqWxk3TezJ6zkjQcIlGTsktikbJmvfZ7sbmpbwB/OZxwzvqzbjxSskZUsEy6e1J6i38ZZ0JL4iONF/CXPs7En9YfID8ZeNGSesmZcVW0RjUp8sznzH4CTU001LRlzsiGrU9myC5sTY31mEm6co2enM0SzpktXC/cqMD04j5maSUPhbuZxqP4kiB1xI92ojeIsfpK3qLaRf8A23uiv9qxIPug+BB+sqpVE9yctNkNbaNQA5qZHkbfKVlKb3sXUI9SCpt8jT3fL85pmqvaxXgwJ6O03IBCMwHQcfCQlNuxDpxNBvfvf7IZKQJqcDcHsc9ep7p24Ts/iO89F9zGpW4a9nVnA4jE1ay3aqxJ6k2/dGnpPWjGnSfsxSMGp1FrIr1WKstidOenrfiTe83u5JmeVQaPU04i5HX+eEzu76Gqy63AxSsfd8yDwkOm0tyeNGTtYgxdRb3F/AXAM0pRdjGtUjur/Qi9uLW598vl1uRGd1l5mYIN76jXgbW/heVV1qS+jPGQGwuO4/SSnJPYiUYNZbnuzyyPmUlW5MpsfUS1RZo5WrroylNKEm0fVtx95GrfqqpBqqLhtBnXrp8Q5+N/D5vH4NUZKcF7P2f46HpQnnjZ7nW7S2lToUjVqtZR6kngAOZMmgnVdluYS0Plm0t9cY7F6ZULc2UgWsD3kX09Z6ncMO9J3f1MuNUSvFI3mwP0iZWUV1yN94a28V4gevGc77PnRnnoSv4PfzLurGcctRW+x9p2bjFrU1qKQQwvcG48jzE9ujU4kFI8epDJJxLU1KCAIAgGp2zss1LMls3A35j8552OwTrq8N/udmFxPC0lsaHE0WpGzix+R8J4lShOi3nR6UKkaq9llVdoL1t4/wAZzRrwubuhIuU3B1M3jJPVmEotbGT1wOE1z9CmV8yNsWolsySuMruUau1RmIAZjb3UBY+glOI3K0Vf5amnCsrt2+ehMuFxLC/s1pg/fbX0W/ztOqGDrtbJGUq9FPdv98SVMA/xVB5Lw8yfwmq7PfxT8l/kyeLj8MfUybCW+I+g/KW7hH+T9CveX/FephUpvyYeY/G8iWBf8iyxC5oUM2uaw6Eajz6TGWEnHbUvx4lDaeBdu0GU27/znn1sO2731OulWWxnhqrkagC/U/kJmoyXMvPKnoZq1Tovfqfykwi/Aq3DxMhTc8WH8+Jl1Q1u2Vc0tkeVKI+JtB1t+AEu1CMfaZCk29CI4mkugGvcB9ZSVemtEiyhN7sgqbWVTYL53lO8WWiNI0HLmc9trZNDGPdlKOSO2p5f3rix9L987sFiama3Iyr0klfmX8DuHhFHad30txH/AMBaehOtSj7zRxp1OSMjuJh7nsPr95wPkWmDxdnZRf8A6r+y9k1q16v+jH+qGGp8aQJ7yp+hMyrdoSp+9F+aNKdNT91+jPE3Swraiivf2l/ykyIdpOey9V+SZUcu79GZVt1MNzooPQTbv6W+hnwr7HtLdDDk6UVPgRCxspbJvyIcFHd2M6+6KBSfYWHUAWlJY2rGOZwdvp+S0YwbspK5VpbuUh/ZqR00/GYx7Xi+ppLCtHrbuYe/aw4/dH4Tb/Uqb5sp3eXgbPA7u4WmyulJVdeB5jlp5StTEQqRs5bkpTXItbY2Dh8UqiumfLw7bLa/E9kgS+FnTpK0fMzqJs0WI/RxhyL0atWmeVyGXzuLkec74tT1Ms7RpMZuZiFGQFGBI1XsnoLhuHrIcJJWRrGrC92fbd38CtDDUqShQFRb5L5SbXYgnU3Nzc9Z2wjlVjyaks0mzYS5QQBAEAQCrtDCLUWzC9te/wBRM6tKNRWki8Jyg7o0D7DpG+W/Eg6g2PSeY+ysPy+539+rLckXYq82byt+ULsykub9CHjZ9EY1NlIOvrNVgaS0V/MjvU2KGyad7lAfHX6yVg6Kd3FP5lXiqjVrmxpKF0AAHQCw+U6YpR2MJNvVkG0nsAeRNvOxI+hh6CJRZpBexGxkAjYwSRkypJVxShgQefTjMa1GFRWkjWlUlB3RVpEqLXvPNh2fKLd5aep2SxKklZGQrEcJ0Rw1KBk6smYtiD1MsoRWyCu9yrWxB6yHboWSZq8Y979eo0M5p04N3sdMG0Vdl4ZnqLTzkljqx5AanQacBIcYQWZIvKbaO1p0KdJbKo8/qTzM4Kldt6Gai5Gl2zvTh8PfO6lgPc4t5KJNDDVa3uxv4vb+iZ5KfvO33OWrfpArsc1LD0wg5MoYkdSOPoTx4z1Y4CkmuI1fwSt5u7OR17u0W182/wCtCliN+sYxBC4dRYkWokXtobXNjqOffOiWDw6s8v2/BMHUbau/UqPvzjLWYUuPvZLE9dAbd3CJYDDT3X2/AVWrEsJv3iAP9lTN+pcW9GF5hHs2lHS7/fkXdacknZfvzJBvtWIW9FO8hmueP3r2kS7PpPS+37zZaNaa1tv+9COpv5iDfLTpaDiwB18gpmsezaS993+i/Bnx5Sdo6fV/ks7N38sbVV4fEnDr7pNx5XnDX7F1vSf0ZvDGK3tLyO62ZtdKihlYMDwM8rJUpyyyRu8rV0baiyma05x5oxldbFLb20KdFbuQF08STwHfNo0pVpZYq6IUsqzM+cbW3yrGoDQLKq6FSL5iTppa45c+c9ehgYxjaW/VO1jKpPnyNxsDf3PYV17J4svLxBN7eBv3GbRhVpaqWZdHb7/kzmoy5Wfgfadkkexp24ZRb0noUpZoJ2seVUVptFuaFBAEAQBAEA5fadY4WuarX9hVyg2+BxwNulgbzmm+HK72Z6FCHHp5I+9H1Ra27imp4Z6lM6qAwIUPpcXIW4B075absrmWHpqdVQlz+n5NduxvAmLp9rKtZdGS/H+8oOuU/LXxNadRSOjG4KeGl1i9n/T8Tfos0OE+RbY35r0Mc+V3amlV0ek4TIVRsvYsLqbA6k8R4gYZnc+iodmwqYdXSu0mmt9r6nb0t48Ni0PsKoZkZSVIKuBfLfKwFx2uI01lsyZ5FXCVqD/3F+CyYMTTbx7dp4Snne7E3yourNa1z3KLi5PUcyBKt8jehQlVdkcTgN/K1TFUkAVqdRlVlKZWUscpsQ7XtobnvFhxkNNK56EsFBQb5o+gsYueW0QVDIbLJGg23vBRw9812YWJVSuYAmwJDMD6XlLNnVSw8p6lvBYpatNaq3yuLi+h85jJ2dmS6bi7HtdwASSABreZ7lkjnKe8lOpWWigLZr2YFSugJ4Akjhzse6WlSkouTOjgtK7LdaYWCNRjtrnDOrILuNba2twNyOAOo85PA4sWnovUltrW2hHtze+riAtOgr0w1iz2uQvxWIuNOspRwFOm3Ko07bLx8Tlq4xxTjFWfX8Gtwmx6dPOxBdmsbscxHE6ke9e4vfumtTF1JWjHT5Hlym9y7Tx4p2y0qYbQZrWY9xsJzujOpvJ26GcqnUb1bHbIlWmguLGpSGup1uvI9CO/vN9sFiLN0Zy+T/JtDENas4+pWc6NSdT8OZba6Cwva5/hPVjCK2kvEvLF33R0m727dSqENYhVPuj4rHUXbgo8L/hPOxeNjB5aer9EVWKqW0MNu1EpVfYFcgyoVI1Uj4rdW1I16ScNTm452773/o5+8ThK5hhMFRqNo5U6aNqG7iRz48fSaSr1IrVF1i535Ctu4CwCNZdcw+6vdxza2AHfKrG2V5L5fv8AZKxMrWNzsrYHsLFWqa8Sbi3Sw0BHfOPEYmVVe0lbzK8SW12kX93duYpgSppEWJSnULK7BbA9vW1ri5IOpAPGK1ChB2d/FrVL6HVTxckrP/JpN7cbiMTWVatGpSYL2AD2P71m4MTwvpoOhnfh40aFK8ZX6vn5CWJzs0mMwjI6I+rkXso7u1oOGhvbQa900pT4kXNbFlio7M3e6GDo/aU+0XWmpzVBYlsoGaxAGi3IuTrYyeJGNsz0M6mJi/d3Ps27231erUVajVKZYBCQb3J6nkL/AEkUMT/uON21yOM6yeiBAEAQBAEAo7ZwwekQwuOfhqG87EylSN46mtCbhNNFbAYT2dJaR1ABGv3bm3ytM4xsrGlWfEm59dTid5N071mfC3p1EFJlVdBYlkLAjVWBUEnhYknjOadN3vHwPewXaeWkoV9YvMm3vydvk76c/I7bZVVmo02exYopJAsCSONuV+NuV50xd1c8KtGMaklHa7Od3z3fw9REDIAauIpqagAzqHZybEjS5du67Ss0jtwOJqU5Np7Rbty0S/Hocnsnct8Ni3a5yKKrUybglEemgzW0OZXY8OKXGko4s7cRj41qCXN2v82nt8mvU7e+ks2eMjmdu1kq1fs1OmlWsVBcuL0qSfCzjgx1uqdTfS9zi+p30U4Qzydl9z5fjN3XFY0qV6q3OV8pGYKBnYLckoCbZhoxGlzpNFLTU9JVVlu9D6fu7TqU8NSSsSagXW5uRqSBfnYWHlKXPIrOMptx2JtoVgqMS4QAaufhHM68/wAeszlItShd7Hyzb+xmRs6K2V9Qrm9XU2zFbXUMSAASWPPW9tadVbM9aL0Ow3QpYhKJWvewICA2uFAsfLp4dJyVnFy9k562VvQby0xVUUiSS2oRTa9viZuSDTl4XNrKcsupFLR3OIwewqzVCqHRTrUFwO4jnw1HdY8xOuVaKjqbtpLU7uoJ59zFGoWoWdnQAqLr+2eDf4RwtzPhLThmhlb1+xWrG8cpDj1qpTHsqAbNp+rzEAC3ELoBy4j6zOjTUnmlIxhhpOd6hXpYrEsQ32N/Zk6kI/AC3vEWuCPw75rLC00ve1E8BTfxGBxgar7NSF0XiCGLG4YWfmP5vyrwXGGZq7/ehxVMA4q5sm24jOVSpSKj3i7Zb9ntBbHW97c+EwjhZRjeSevJf2ZLDTbskazbGPwy5L0xXUjMBmylb8LkglW0tw4a9J04ehW11y8vmbLs6p8WhcxO22p2u4tpY2up6hbcQJzxwvEk9P3xMVQnmypFXbG2sPiSA1EqOJfsjtk3bsC9gTzzczpfWdUKNWkrqWp0y7Iq8NyW/Q1WIxVGkyikuYBgz9piOzqBcnTXWwsNNZpBVKied/I5oYCUl7St8yzjNtBjkoCwJU5jx62tbQA/SVpYVxV6m504bsxzftOxM23ay8Dc2tqSQOfu3t/Ile6wenI712JF6uXoYbL24aTVKzAvWbQXICAa/COV7mwA8ZNfDcVRgtIrzM/9HtLSWhPsveWoX/XVmCk6KAvsh5aEWNrG54a3lK2EiqeWnFf2c9bs2cdYO/gX9r432xQ4amKtSxDVFUs4UnRbWsoPrpbTmw1K1PJNWt6l8LgYayxGnoamlt2tTYhgDbQhgQQeYM1eEg7HoT7MoSfs7WPuH6PMIj4ShiSCGdScumVdWXQAd07KGHjD2t2fN4imqdWUVyOunUYiAIAgCAIB4RANFX+1IxCCk6jgGLK9h/esQZyy4ieln6HfT7vKPttp+Fmv6ZTqYutnWpUwzU/ZhszB1dTTa2caWNxYPw+AjnKZpXu42t9jXh0srhCone1lZp3W3h4b878iQ7xKPew+JXv9lceRUkEeEtxlzT8ivc3ynHz/ADY122tuUcRTNKn7QVrq9INTqKDUpEVVXMVsLlLcfikSmpKy3N6GFqUZcSdsuzs09JaN2Tvpe5ntDfDDkezC1naoikZKbFbVVBUluFu1r0sektKorGUcBVXtOys2t1yeuhrt4NrDDYZqtrtYBF+87aILc9dfAGUbKUKeeaic3sPbOEwyNTqYhTiCxNdiGuavxDNlsQp0FtNO+UOytCpN3itOReG8OCuWFeldrXNwCbcLk8bSTndGr0Zku3MMxAWvSJJsAHW5J4DjKu5Koz5o0j7Wo1a2erVRaNM/qlZgPauCQapHNQQQveCZlKMraHdGDhHTdlmrt7B3DGtTJHA8bHhfxtpfvmXDntYJTSsR1d5cPlZkfOQPdUNck6KOHEn8eklUpXsQqcmzW4DatJMzOWesx7ZWm5AtwRTa2VeGnHU85aUG9ti8oN6IkbbqD3aNc+FIjjx4yvCfNrzGV8ynjNrM4yLTqI7mylwAbfGwF+Q+ZEmNJLVtNIlJLU92bUrZkUUkpothYtmbKO5dLytVwUW73ZKScjtaW2MoVVopltrr9BawmHFSVrFHh7u7ZZpbaZkyuoPC9iQLeBErKvpltoR3RZrpmFDH0jdWplFJ5AFe654+chVV8hLDSS0dyptWjghTJy0yTwyqpJPLSX4kuohTqX0KexqmDKWq0DmB5qOB4cJLqq+rLzo1eTNjiBgAvYVLa3XI2t+NxbW8Od9UzFUp39ooYbDYdLsmHXN8PZRT6nhKPEN6SbNZQnyZaO1Ki5QKQt8Quv8AJlOKntIKn1I8ZVptZnw6Ow6hc1+68mOIa0zDgxLYbC5e3QQ/4U/ES0MUrasrKlO/stniYHZ5P/dafj7NJt3mPUztW5v1Iq2y8FmGXCUiOfYUSe8orlqveRZothqV1pUVQcTlyqLjTUDnEsRCwVGo99T2vjKDuM1EG47VwpvbhxGo8YWKT2J4M47M6vdDGKytSRQqUwuUCw0OYEBQLACw9Z6GDrqomlyPNxtJxak+Z0U7TiEAQBAEAQBAI6yE8OP885DVyU7Gvq1qi8aDN+w1M/52WUsy90ysm0qaAKadZANAPZVGAHS9MMAPOVsloWbcndmQ27huBr01PR2CH0exkkWJNlUERStN8yFmYAEELnOYqLfDckjpe0hRsXqVHUd3vZLyOQ2lsxKppe0DH2L5lF9M66Akc7TBnTTqOF8vMxxAU+8F8wPxlLhN9TWVzhh7wo+YSVuy6cupq8di8FlIzUkuCMyZA4vobG2htcX749ovGo073KdPbWDTRXQgAKospyhRYAG1z5mU4c3yLyrp8zxt5qPwgn9lCfoJPBn0K8dfyKeI2sKjI3sarFCSvYewPC9rWJ6X4QqEy/eYpWuZNtOu3DD1v3CPrHdn1RXvEfHyIjVxZ4Yap55R9TJ7uuqI7wuSZj9jxZN/s9ja1yyXt6yeDHbMT3l9GXNmYLFLUVqiKqa37VzwNtPG0wxNKKpuzNcPWbqK6Olp055D0PT0ZdoUhCuVk7E32UHlLZTPPYifArxtw7ukjKWVQhq4McLd/nJukybtlY4MDXnIzWLb7kFbD2lcxokUqqsDofrLqUeZOUiKtcXvpw4+sm6sLEozHmefrM3YlKxJTDDqPx6GRcrZczIuecjwJsj1T1HpJaILNM90JlJJHXbhHtVP2V+pntdlby+h4vanw/U7OeweQIAgCAIAgCAIAgGJWQ0TcjqUAeIB8ZFicxrcRu3hXN2w9InrkAPqBeRlJzmuxO51A/C9ugq1QPQNaVcCyma6r+j3CNxo5v2mc/VoystnIh+j3BrwwtLzQH6yLSF4k6bpUV92jTHhTT8pXLIspImGwByAHgqj8JGRk50DsLx9BHDZKqGP9BeMrwyeKe/0F4xwxxDw7C/m0cMcUxOw4dMtxDCpsW4IPOZypXVmaRrZXdGnxOycQh7KZx1UqD6MRb5zzZ4KfI9KGNp21K/tK68cNW8lzf5CZl3Or+s171RfP0YO1mX3qNYf8mp+CyO7Vly9URxaD5ng3hT4g6/tU3H1WFQrdCHOl/JGP9ZsNzqoPEgfWO71f4vyHEpvaS8zD+seGb3a9I+Drf6yksPU/iy8Jw6o8baFM8HU+BBmLpT6G6nHkyu+ITr8pXJI0UyM11/nnDiyMxh9oHT+f5+kOIzGP2xRxI4c/l/PfHDfIq5IwfaNP7y/vCaRoVOj8ijrQW8l5mdLFg2yqzfsIzf5QZp3Wq/hM3iaf8jaYajVb3aNTxZSv+a0vHBVehnLFU+p3W6OC9krZh22tc8rDgB6z2cFRVJPqzxsbV4klbZHRzuOEQBAEAQBAEAQBAEAQBAEAQDy0AZRAGUQDzIOkAZB0gDIOkE3GQdIsQPZjpFhcxNEdJFkTdnn2dekjKic7MThl6SHBE52Y/ZF6CRkRPEZi2BXoPSRw0TxGRNs1T8I9I4aJ4rIn2LTPFEPio/KOEieMyu+7NA8aNI/4E/KRwxxmQndTDf7ij/00/KOGTxmYndDDH+wpf8ATT8pHDHGZmm6mHHCjTH+Bfyk8MOsydN3KI/s0/dX8pKpkcUnTY6DkPSTwyOKTDZidI4aI4rJEwKjlJyIh1GTJSA4SVFIo5NkksQIAgH/2Q==" }
  #
  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  describe "save_cover_photo" do
    it "updates the group with an cover_photo" do
      group.cover_photo = image
      timestamp = Time.now.strftime("%Y%m%d%H%M%S")
      put :save_cover_photo, params: {id: group.id, cover_photo: {image: image, filename: "#{group.id}#{timestamp}"}}
      group.reload

      expect(group.cover_photo).not_to be_nil
    end
  end

  let(:valid_attributes) { FactoryGirl.attributes_for :valid_group, user_id: user.id }

  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  let(:invalid_attributes) {
    FactoryGirl.attributes_for :invalid_group
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all groups as @groups" do
      group = Group.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:groups)).to eq([group])
    end
  end

  describe "GET #show" do
    it "assigns the requested group as @group" do
      group = Group.create! valid_attributes
      get :show, params: {id: group.to_param}, session: valid_session
      expect(assigns(:group)).to eq(group)
    end
  end

  describe "GET #new" do
    it "assigns a new group as @group" do
      get :new, params: {}, session: valid_session
      expect(assigns(:group)).to be_a_new(Group)
    end
  end

  describe "GET #edit" do
    it "assigns the requested group as @group" do
      group = Group.create! valid_attributes
      get :edit, params: {id: group.to_param}, session: valid_session
      expect(assigns(:group)).to eq(group)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Group" do
        expect {
          post :create, params: {group: valid_attributes}, session: valid_session
        }.to change(Group, :count).by(1)
      end

      it "assigns a newly created group as @group" do
        post :create, params: {group: valid_attributes}, session: valid_session
        expect(assigns(:group)).to be_a(Group)
        expect(assigns(:group)).to be_persisted
      end

      it "redirects to the created group" do
        post :create, params: {group: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Group.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved group as @group" do
        post :create, params: {group: invalid_attributes}, session: valid_session
        expect(assigns(:group)).to be_a_new(Group)
      end

      it "re-renders the 'new' template" do
        post :create, params: {group: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { FactoryGirl.attributes_for :valid_group, user_id: user.id }

      it "updates the requested group" do
        group = Group.create! valid_attributes
        put :update, params: {id: group.to_param, group: new_attributes}, session: valid_session
        group.reload
        expect(response).to redirect_to(group)
      end

      it "assigns the requested group as @group" do
        group = Group.create! valid_attributes
        put :update, params: {id: group.to_param, group: valid_attributes}, session: valid_session
        expect(assigns(:group)).to eq(group)
      end

      it "redirects to the group" do
        group = Group.create! valid_attributes
        put :update, params: {id: group.to_param, group: valid_attributes}, session: valid_session
        expect(response).to redirect_to(group)
      end
    end

    context "with invalid params" do
      it "assigns the group as @group" do
        group = Group.create! valid_attributes
        put :update, params: {id: group.to_param, group: invalid_attributes}, session: valid_session
        expect(assigns(:group)).to eq(group)
      end

      it "re-renders the 'edit' template" do
        group = Group.create! valid_attributes
        put :update, params: {id: group.to_param, group: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested group" do
      group = Group.create! valid_attributes
      expect {
        delete :destroy, params: {id: group.to_param}, session: valid_session
      }.to change(Group, :count).by(-1)
    end

    it "redirects to the groups list" do
      group = Group.create! valid_attributes
      delete :destroy, params: {id: group.to_param}, session: valid_session
      expect(response).to redirect_to(groups_url)
    end
  end

end
