require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OwnVesselsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OwnVessel. As you add validations to OwnVessel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OwnVesselsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all own_vessels as @own_vessels" do
      own_vessel = OwnVessel.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:own_vessels)).to eq([own_vessel])
    end
  end

  describe "GET #show" do
    it "assigns the requested own_vessel as @own_vessel" do
      own_vessel = OwnVessel.create! valid_attributes
      get :show, params: {id: own_vessel.to_param}, session: valid_session
      expect(assigns(:own_vessel)).to eq(own_vessel)
    end
  end

  describe "GET #new" do
    it "assigns a new own_vessel as @own_vessel" do
      get :new, params: {}, session: valid_session
      expect(assigns(:own_vessel)).to be_a_new(OwnVessel)
    end
  end

  describe "GET #edit" do
    it "assigns the requested own_vessel as @own_vessel" do
      own_vessel = OwnVessel.create! valid_attributes
      get :edit, params: {id: own_vessel.to_param}, session: valid_session
      expect(assigns(:own_vessel)).to eq(own_vessel)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OwnVessel" do
        expect {
          post :create, params: {own_vessel: valid_attributes}, session: valid_session
        }.to change(OwnVessel, :count).by(1)
      end

      it "assigns a newly created own_vessel as @own_vessel" do
        post :create, params: {own_vessel: valid_attributes}, session: valid_session
        expect(assigns(:own_vessel)).to be_a(OwnVessel)
        expect(assigns(:own_vessel)).to be_persisted
      end

      it "redirects to the created own_vessel" do
        post :create, params: {own_vessel: valid_attributes}, session: valid_session
        expect(response).to redirect_to(OwnVessel.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved own_vessel as @own_vessel" do
        post :create, params: {own_vessel: invalid_attributes}, session: valid_session
        expect(assigns(:own_vessel)).to be_a_new(OwnVessel)
      end

      it "re-renders the 'new' template" do
        post :create, params: {own_vessel: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested own_vessel" do
        own_vessel = OwnVessel.create! valid_attributes
        put :update, params: {id: own_vessel.to_param, own_vessel: new_attributes}, session: valid_session
        own_vessel.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested own_vessel as @own_vessel" do
        own_vessel = OwnVessel.create! valid_attributes
        put :update, params: {id: own_vessel.to_param, own_vessel: valid_attributes}, session: valid_session
        expect(assigns(:own_vessel)).to eq(own_vessel)
      end

      it "redirects to the own_vessel" do
        own_vessel = OwnVessel.create! valid_attributes
        put :update, params: {id: own_vessel.to_param, own_vessel: valid_attributes}, session: valid_session
        expect(response).to redirect_to(own_vessel)
      end
    end

    context "with invalid params" do
      it "assigns the own_vessel as @own_vessel" do
        own_vessel = OwnVessel.create! valid_attributes
        put :update, params: {id: own_vessel.to_param, own_vessel: invalid_attributes}, session: valid_session
        expect(assigns(:own_vessel)).to eq(own_vessel)
      end

      it "re-renders the 'edit' template" do
        own_vessel = OwnVessel.create! valid_attributes
        put :update, params: {id: own_vessel.to_param, own_vessel: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested own_vessel" do
      own_vessel = OwnVessel.create! valid_attributes
      expect {
        delete :destroy, params: {id: own_vessel.to_param}, session: valid_session
      }.to change(OwnVessel, :count).by(-1)
    end

    it "redirects to the own_vessels list" do
      own_vessel = OwnVessel.create! valid_attributes
      delete :destroy, params: {id: own_vessel.to_param}, session: valid_session
      expect(response).to redirect_to(own_vessels_url)
    end
  end

end
